import io.github.themrmilchmann.gradle.publish.curseforge.ChangelogFormat
import io.github.themrmilchmann.gradle.publish.curseforge.ReleaseType

apply plugin: 'com.gradleup.shadow'
apply plugin: "io.github.themrmilchmann.curseforge-publish"
apply plugin: "com.modrinth.minotaur"

architectury {
    platformSetupLoomIde()
    fabric()
}
sourceSets {
    main {
        resources.srcDir project(':common').file('src/main/resources')
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    implementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"

    common(project(':common')) { transitive false }
    shadowBundle(project(':common')) { transitive false }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

jar {
    archiveClassifier = 'dev'
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = ''
}

build.dependsOn shadowJar

curseforge {
    apiToken = System.getenv("CURSEFORGE_TOKEN")

    publications {
        register("curseForge") {
            projectId = "1367332"

            gameVersion rootProject.curseforge_minecraft_version_type, rootProject.curseforge_minecraft_version
            gameVersion "modloader", "fabric"
            gameVersion "environment", "client"
            gameVersion "environment", "server"

            artifacts.register("main") {
                displayName = "Fabric-${project.version}"
                releaseType = ReleaseType.RELEASE

                changelog {
                    format = ChangelogFormat.MARKDOWN
                    from(rootProject.file("GabousLibs.md"))
                }

                from(tasks.named("shadowJar"))
            }
        }
    }
}

def packagedJar = tasks.named("shadowJar").flatMap { it.archiveFile }

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "N8aGZtvj"
    versionNumber = "Fabric-${project.version}"
    versionName = "Gabou's Libs ${mod_version}"
    changelog = rootProject.file("GabousLibs.md").text
    gameVersions = ["26.2"]
    loaders = ["fabric"]
    versionType = "release"
    uploadFile = packagedJar
}


