# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.7.1
maven_group=net.Gabou
archives_name=gaboulibs
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.1.2
# Dependencies
architectury_api_version=20.0.4
fabric_loader_version=0.19.2
fabric_api_version=0.149.1+26.1.2
neoforge_version=26.1.2.65-beta
