import io.github.themrmilchmann.gradle.publish.curseforge.ChangelogFormat
import io.github.themrmilchmann.gradle.publish.curseforge.ReleaseType



apply plugin: 'com.gradleup.shadow'
apply plugin: "io.github.themrmilchmann.curseforge-publish"
apply plugin: "com.modrinth.minotaur"

architectury {
    platformSetupLoomIde()
    neoForge()
}
sourceSets {
    main {
        resources.srcDir project(':common').file('src/main/resources')
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration are bundled by Shadow.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}
repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    implementation "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"

    common(project(':common')) { transitive false }
    shadowBundle project(':common')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

curseforge {
    apiToken = System.getenv("CURSEFORGE_TOKEN")

    publications {
        register("curseForge") {
            projectId = "1367332"

            gameVersion "minecraft", rootProject.minecraft_version
            gameVersion "modloader", "neoforge"

            artifacts.register("main") {
                displayName = "NeoForge-${project.version}"
                releaseType = ReleaseType.RELEASE

                changelog {
                    format = ChangelogFormat.MARKDOWN
                    from(rootProject.file("GabousLibs.md"))
                }

                from(tasks.named("shadowJar"))
            }
        }
    }
}

def packagedJar = tasks.shadowJar.archiveFile
modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "N8aGZtvj" // from your Modrinth project URL
    versionNumber = "NeoForge-${project.version}"
    versionName = "Gabou's Libs ${mod_version}"
    changelog = rootProject.file("GabousLibs.md").text
    gameVersions = ["26.2"]
    loaders = ["neoforge"]
    versionType = "release"
    uploadFile = packagedJar
}

